### ISSUE TITLE
Support swapping out packages rather than files.

### ISSUE THREAD

**Issue by terinjokes** [thlorenz/browserify-swap#1]
Right now browserify-swap replaces files that match a regex, so to replace `underscore` you'll have something like

``` json
{
  "all": {
    "underscore.js$": "lodash"
  }
}
```

Since the package structure is not usually part of the public API, it would be nice to be able to replace based on package name, like with the browser field. This would become:

``` json
{
  "all": {
    "underscore": "lodash"
  }
}
```

**Comment by scamden** [comment]
+1

**Comment by ljharb** [comment]
Personally I'd be very interested in _only_ this feature - ie, I want to swap out npm-installed packages, but i'd never want to swap out local files where I have full control of the code.
